export const IpoSchema = {
  id: null,
  name: null,
  series: null,
  facevalue: null,
  min_price: null,
  max_price: null,
  total_issue: null,
  fresh_issue: null,
  issue_type: null,
  listing_at: null,
  gen_holding_pre_issue: null,
  gen_holding_post_issue: null,
  opening_date: null,
  closing_date: null,
  basis_date: null,
  initiation_of_refunds: null,
  shares_to_demat: null,
  listing_date: null,
  promoter_holdings_preissue: null,
  promoter_holdings_postissue: null,
  anchor_bid_date: null,
  anchor_lockinhalf: null,
  anchor_lockinrest: null,
  pe: null,
  marketcap: null,
  roe: null,
  roce: null,
  eps: null,
  ronw: null,
  bse_script_code: null,
  nse_symbol: null,
  final_price: null,
  preopen_nse: null,
  preopen_bse: null,
  company_address: null,
  company_phone: null,
  company_email: null,
  company_website: null,
  registrar_address: null,
  registrar_phone: null,
  registrar_email: null,
  registrar_website: null,
  registrar_name: null,
  drhp: null,
  rhp: null,
  anchor_list: null,
  shares_in_lot: null,
  dayend_price: null,
  cut_off_mandate: null,
  defunct: null,
  retail_discount: null,
  employee_discount: null,
  anchor_portion: null,
  debt: null,
}

export const CompanyFinancesSchema = {
  ipo_id: null,
  period: null,
  assets: null,
  revenue: null,
  profit_after_tax: null,
  net_worth: null,
  reserves: null,
  borrowing: null,
};

export const IpoLotsSchema = {
  ipo_id: null,
  category: null,
  lots_min: null,
  lots_max: null,
};

export const SubsciptionSchema = {
  ipo_id: null,
  category: null,
  shares_offered: null,
  shares_bid: null,
  updated_at: null,
}
